name: pg-backup

services:
  pg-backup:
    container_name: pg-backup
    image: postgres:16-alpine
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    deploy:
      resources:
        limits:
          memory: 256M
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - .env
    entrypoint: crond -f -l 2
    volumes:
      - ./backups:/backups
      - ./backup.sh:/backup.sh:ro
      - ./crontab:/var/spool/cron/crontabs/root:ro
    labels:
      - "traefik.enable=false"

      # Watchtower automatic update
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      lan:
      paperless_backend:
      immich_backend:
      the-box_backend:
      copro-pilot_backend:
      n8n_backend:
      toko_backend:
      wawptn_backend:
      koe_internal:
      yamtrack_backend:

networks:
  lan:
    external: true
  paperless_backend:
    external: true
    name: paperless-ngx_backend
  immich_backend:
    external: true
    name: immich_backend
  the-box_backend:
    external: true
    name: the-box_backend
  copro-pilot_backend:
    external: true
    name: copro-pilot_backend
  n8n_backend:
    external: true
    name: n8n_backend
  toko_backend:
    external: true
    name: toko_backend
  wawptn_backend:
    external: true
    name: wawptn_backend
  koe_internal:
    external: true
    name: koe_koe-internal
  yamtrack_backend:
    external: true
    name: yamtrack_backend
