server {
    listen 80;
    listen [::]:80;
    root /usr/share/nginx/html;
    index index.html;
    autoindex off;
    server_tokens off;

    add_header X-Robots-Tag "noindex, nofollow, noarchive" always;
    add_header Referrer-Policy "no-referrer" always;
    add_header Cache-Control "no-store" always;
    add_header X-Content-Type-Options "nosniff" always;

    location / {
        try_files $uri $uri/ =404;
    }
}
