name: radarr

services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /usr/local/radarr/data:/config
      - /mnt/movies:/movies
      - /mnt/downloads:/downloads
    labels:
      - "traefik.enable=true"

      # Entrypoint
      - "traefik.http.routers.radarr.entrypoints=websecure"

      # Router
      - "traefik.http.routers.radarr.rule=Host(`radarr.battistella.ovh`)"

      # Service
      - "traefik.http.services.radarr.loadBalancer.server.port=7878"
      
      # Watchtower automatic update
      - "com.centurylinklabs.watchtower.enable=true"

    networks:
      lan:

networks:
  lan:
    external: true
