---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey

layout:
  Multimedia:
    tab: Personnel
  Personnel:
    tab: Personnel
  Utilitaires:
    tab: Personnel
  Infrastructure:
    tab: Professionnel
  Projets:
    tab: Professionnel
  IA:
    tab: Personnel
